LVGL_PATH ?= ${shell pwd}/lvgl

ASRCS += \
lv_blend_helium.S \
lv_blend_neon.S
 
CSRCS += \
lv_uefi_indev_keyboard.c \
lv_uefi_display.c \
lv_uefi_context.c \
lv_uefi_indev_pointer.c \
lv_uefi_indev_touch.c \
lv_uefi_private.c \
lv_windows_context.c \
lv_windows_input.c \
lv_windows_display.c \
lv_x11_input.c \
lv_x11_display.c \
lv_sdl_mousewheel.c \
lv_sdl_mouse.c \
lv_sdl_keyboard.c \
lv_sdl_window.c \
lv_qnx.c \
lv_lcd_generic_mipi.c \
lv_linux_fbdev.c \
lv_st_ltdc.c \
lv_ili9341.c \
lv_ft81x.c \
lv_linux_drm.c \
lv_renesas_glcdc.c \
lv_st7796.c \
lv_st7735.c \
lv_st7789.c \
lv_evdev.c \
lv_nuttx_lcd.c \
lv_nuttx_cache.c \
lv_nuttx_profiler.c \
lv_nuttx_touchscreen.c \
lv_nuttx_entry.c \
lv_nuttx_libuv.c \
lv_nuttx_image_cache.c \
lv_nuttx_fbdev.c \
lv_wayland_smm.c \
lv_wl_shm.c \
lv_wl_keyboard.c \
lv_wl_seat.c \
lv_wayland.c \
lv_wl_pointer.c \
lv_wl_xdg_shell.c \
lv_wl_dmabuf.c \
lv_wl_window_decorations.c \
lv_wl_window.c \
lv_wl_touch.c \
lv_wl_cache.c \
lv_wl_pointer_axis.c \
lv_wl_shell.c \
lv_libinput.c \
lv_xkb.c \
lv_opengles_texture.c \
lv_opengles_debug.c \
lv_opengles_driver.c \
lv_glfw_window.c \
lv_init.c \
lv_indev.c \
lv_indev_scroll.c \
lv_indev_gesture.c \
lv_display.c \
lv_os.c \
lv_windows.c \
lv_freertos.c \
lv_cmsis_rtos2.c \
lv_rtthread.c \
lv_linux.c \
lv_pthread.c \
lv_mqx.c \
lv_sdl2.c \
lv_os_none.c \
lv_math.c \
lv_text_ap.c \
lv_log.c \
lv_area.c \
lv_palette.c \
lv_profiler_builtin.c \
lv_timer.c \
lv_templ.c \
lv_utils.c \
lv_lru.c \
lv_cache_entry.c \
lv_image_cache.c \
lv_image_header_cache.c \
lv_cache_lru_rb.c \
lv_cache_lru_ll.c \
lv_cache.c \
lv_event.c \
lv_ll.c \
lv_anim.c \
lv_style.c \
lv_async.c \
lv_bidi.c \
lv_color.c \
lv_tree.c \
lv_array.c \
lv_circle_buf.c \
lv_fs.c \
lv_iter.c \
lv_anim_timeline.c \
lv_color_op.c \
lv_grad.c \
lv_style_gen.c \
lv_rb.c \
lv_text.c \
lv_matrix.c \
lv_refr.c \
lv_obj.c \
lv_obj_style_gen.c \
lv_obj_event.c \
lv_obj_pos.c \
lv_obj_class.c \
lv_obj_draw.c \
lv_obj_scroll.c \
lv_group.c \
lv_obj_tree.c \
lv_obj_property.c \
lv_obj_style.c \
lv_obj_id_builtin.c \
lv_flex.c \
lv_layout.c \
lv_grid.c \
lv_calendar_header_arrow.c \
lv_calendar_chinese.c \
lv_calendar.c \
lv_calendar_header_dropdown.c \
lv_spinner.c \
lv_switch.c \
lv_lottie.c \
lv_table.c \
lv_tileview.c \
lv_animimage.c \
lv_textarea.c \
lv_menu.c \
lv_label.c \
lv_list.c \
lv_slider.c \
lv_objx_templ.c \
lv_imagebutton.c \
lv_led.c \
lv_button.c \
lv_scale.c \
lv_3dtexture.c \
lv_msgbox.c \
lv_image.c \
lv_dropdown.c \
lv_canvas.c \
lv_roller.c \
lv_win.c \
lv_spinbox.c \
lv_line.c \
lv_keyboard_properties.c \
lv_slider_properties.c \
lv_image_properties.c \
lv_obj_properties.c \
lv_animimage_properties.c \
lv_dropdown_properties.c \
lv_style_properties.c \
lv_label_properties.c \
lv_textarea_properties.c \
lv_roller_properties.c \
lv_span.c \
lv_chart.c \
lv_checkbox.c \
lv_bar.c \
lv_tabview.c \
lv_arc.c \
lv_buttonmatrix.c \
lv_keyboard.c \
lv_theme.c \
lv_theme_simple.c \
lv_theme_mono.c \
lv_theme_default.c \
lv_tick.c \
lv_font_montserrat_10.c \
lv_font_source_han_sans_sc_14_cjk.c \
lv_font_montserrat_8.c \
lv_font_montserrat_16.c \
lv_font_simsun_16_cjk.c \
lv_binfont_loader.c \
lv_font_montserrat_24.c \
lv_font_montserrat_48.c \
lv_font_montserrat_28_compressed.c \
lv_font_montserrat_32.c \
lv_font_montserrat_40.c \
lv_font_montserrat_38.c \
lv_font_source_han_sans_sc_16_cjk.c \
lv_font_montserrat_28.c \
lv_font_montserrat_18.c \
lv_font_unscii_16.c \
lv_font_montserrat_20.c \
lv_font_montserrat_30.c \
lv_font_montserrat_46.c \
lv_font_montserrat_12.c \
lv_font_montserrat_44.c \
lv_font_montserrat_34.c \
lv_font_montserrat_14_aligned.c \
lv_font_montserrat_22.c \
lv_font.c \
lv_font_montserrat_36.c \
lv_font_dejavu_16_persian_hebrew.c \
lv_font_fmt_txt.c \
lv_font_montserrat_26.c \
lv_font_unscii_8.c \
lv_font_simsun_14_cjk.c \
lv_font_montserrat_42.c \
lv_font_montserrat_14.c \
lv_draw_line.c \
lv_draw_nema_gfx_utils.c \
lv_nema_gfx_path.c \
lv_draw_nema_gfx_layer.c \
lv_draw_nema_gfx_line.c \
lv_draw_nema_gfx_border.c \
lv_draw_nema_gfx_arc.c \
lv_draw_nema_gfx_label.c \
lv_draw_nema_gfx.c \
lv_draw_nema_gfx_fill.c \
lv_draw_nema_gfx_triangle.c \
lv_draw_nema_gfx_img.c \
lv_draw_nema_gfx_stm32_hal.c \
lv_draw_sdl.c \
lv_draw.c \
lv_draw_opengles.c \
lv_draw_vector.c \
lv_draw_triangle.c \
lv_draw_3d.c \
lv_draw_label.c \
lv_draw_buf.c \
lv_draw_vglite_triangle.c \
lv_draw_vglite_img.c \
lv_draw_vglite_layer.c \
lv_vglite_utils.c \
lv_draw_vglite_line.c \
lv_draw_vglite_border.c \
lv_draw_buf_vglite.c \
lv_draw_vglite_label.c \
lv_vglite_matrix.c \
lv_vglite_buf.c \
lv_draw_vglite_arc.c \
lv_draw_vglite.c \
lv_vglite_path.c \
lv_draw_vglite_fill.c \
lv_pxp_utils.c \
lv_draw_pxp.c \
lv_draw_pxp_layer.c \
lv_draw_pxp_img.c \
lv_draw_buf_pxp.c \
lv_draw_pxp_fill.c \
lv_pxp_osa.c \
lv_pxp_cfg.c \
lv_g2d_utils.c \
lv_draw_g2d_img.c \
lv_draw_buf_g2d.c \
lv_draw_g2d_fill.c \
lv_g2d_buf_map.c \
lv_draw_g2d.c \
lv_draw_mask.c \
lv_draw_dma2d.c \
lv_draw_dma2d_fill.c \
lv_draw_dma2d_img.c \
lv_image_decoder.c \
lv_draw_arc.c \
lv_draw_dave2d_border.c \
lv_draw_dave2d_line.c \
lv_draw_dave2d_utils.c \
lv_draw_dave2d.c \
lv_draw_dave2d_fill.c \
lv_draw_dave2d_triangle.c \
lv_draw_dave2d_mask_rectangle.c \
lv_draw_dave2d_image.c \
lv_draw_dave2d_label.c \
lv_draw_dave2d_arc.c \
lv_vg_lite_utils.c \
lv_draw_vg_lite_triangle.c \
lv_draw_vg_lite.c \
lv_draw_vg_lite_arc.c \
lv_draw_vg_lite_layer.c \
lv_draw_vg_lite_label.c \
lv_draw_vg_lite_border.c \
lv_draw_vg_lite_vector.c \
lv_draw_vg_lite_fill.c \
lv_vg_lite_decoder.c \
lv_vg_lite_path.c \
lv_vg_lite_stroke.c \
lv_draw_buf_vg_lite.c \
lv_draw_vg_lite_mask_rect.c \
lv_draw_vg_lite_line.c \
lv_vg_lite_grad.c \
lv_vg_lite_pending.c \
lv_vg_lite_math.c \
lv_draw_vg_lite_img.c \
lv_draw_vg_lite_box_shadow.c \
lv_draw_image.c \
lv_draw_sw_utils.c \
lv_draw_sw_triangle.c \
lv_draw_sw_line.c \
lv_draw_sw_vector.c \
lv_draw_sw_transform.c \
lv_draw_sw_arc.c \
lv_draw_sw_border.c \
lv_draw_sw_letter.c \
lv_draw_sw_img.c \
lv_draw_sw_fill.c \
lv_draw_sw_mask.c \
lv_draw_sw_box_shadow.c \
lv_draw_sw_mask_rect.c \
lv_draw_sw_blend_to_rgb565_swapped.c \
lv_draw_sw_blend_to_rgb888.c \
lv_draw_sw_blend_to_i1.c \
lv_draw_sw_blend_to_argb8888_premultiplied.c \
lv_draw_sw_blend_to_argb8888.c \
lv_draw_sw_blend_to_l8.c \
lv_draw_sw_blend_to_al88.c \
lv_draw_sw_blend_to_rgb565.c \
lv_draw_sw_blend.c \
lv_draw_sw.c \
lv_draw_sw_grad.c \
lv_draw_rect.c \
lv_mem_core_uefi.c \
lv_string_rtthread.c \
lv_sprintf_rtthread.c \
lv_mem_core_rtthread.c \
lv_string_builtin.c \
lv_tlsf.c \
lv_mem_core_builtin.c \
lv_sprintf_builtin.c \
lv_mem.c \
lv_mem_core_micropython.c \
lv_mem_core_clib.c \
lv_sprintf_clib.c \
lv_string_clib.c \
lv_test_indev.c \
lv_test_helpers.c \
lv_test_display.c \
lv_test_indev_gesture.c \
lv_test_screenshot_compare.c \
lv_snapshot.c \
lv_fragment.c \
lv_fragment_manager.c \
lv_sysmon.c \
lv_observer.c \
lv_ime_pinyin.c \
lv_xml_roller_parser.c \
lv_xml_spangroup_parser.c \
lv_xml_image_parser.c \
lv_xml_textarea_parser.c \
lv_xml_slider_parser.c \
lv_xml_event_parser.c \
lv_xml_bar_parser.c \
lv_xml_calendar_parser.c \
lv_xml_obj_parser.c \
lv_xml_arc_parser.c \
lv_xml_button_parser.c \
lv_xml_scale_parser.c \
lv_xml_keyboard_parser.c \
lv_xml_canvas_parser.c \
lv_xml_dropdown_parser.c \
lv_xml_buttonmatrix_parser.c \
lv_xml_label_parser.c \
lv_xml_chart_parser.c \
lv_xml_table_parser.c \
lv_xml_checkbox_parser.c \
lv_xml_tabview_parser.c \
lv_xml.c \
lv_xml_style.c \
lv_xml_component.c \
lv_xml_widget.c \
lv_xml_update.c \
lv_xml_utils.c \
lv_xml_base_types.c \
lv_xml_parser.c \
lv_imgfont.c \
vg_lite_matrix.c \
lv_monkey.c \
lv_font_manager.c \
lv_font_manager_recycle.c \
lv_file_explorer.c \
lv_gridnav.c \
lv_tiny_ttf.c \
lv_bin_decoder.c \
qrcodegen.c \
lv_qrcode.c \
lv_ffmpeg.c \
lv_gif.c \
gifdec.c \
lv_svg.c \
lv_svg_token.c \
lv_svg_decoder.c \
lv_svg_parser.c \
lv_svg_render.c \
lv_rlottie.c \
lv_freetype_outline.c \
lv_freetype.c \
lv_ftsystem.c \
lv_freetype_glyph.c \
lv_freetype_image.c \
lv_barcode.c \
code128.c \
lv_libjpeg_turbo.c \
lodepng.c \
lv_lodepng.c \
lv_libpng.c \
lv_tjpgd.c \
tjpgd.c \
lv_fs_rawfs.c \
lv_fs_uefi.c \
lv_fs_cbfs.c \
lv_fs_fatfs.c \
lv_fs_win32.c \
lv_fs_memfs.c \
lv_fs_posix.c \
lv_fs_littlefs.c \
lv_fs_stdio.c \
lv_rle.c \
lz4.c \
xmltok.c \
xmlparse.c \
xmlrole.c \
xmltok_ns.c \
xmltok_impl.c \
lv_bmp.c \

AFLAGS += "-I$(LVGL_PATH)"
CFLAGS += "-I$(LVGL_PATH)"

VPATH += \
$(LVGL_PATH)/src \
$(LVGL_PATH)/src/drivers/uefi \
$(LVGL_PATH)/src/drivers/windows \
$(LVGL_PATH)/src/drivers/x11 \
$(LVGL_PATH)/src/drivers/sdl \
$(LVGL_PATH)/src/drivers/qnx \
$(LVGL_PATH)/src/drivers/display \
$(LVGL_PATH)/src/drivers/display/lcd \
$(LVGL_PATH)/src/drivers/display/fb \
$(LVGL_PATH)/src/drivers/display/st_ltdc \
$(LVGL_PATH)/src/drivers/display/ili9341 \
$(LVGL_PATH)/src/drivers/display/tft_espi \
$(LVGL_PATH)/src/drivers/display/ft81x \
$(LVGL_PATH)/src/drivers/display/drm \
$(LVGL_PATH)/src/drivers/display/renesas_glcdc \
$(LVGL_PATH)/src/drivers/display/st7796 \
$(LVGL_PATH)/src/drivers/display/st7735 \
$(LVGL_PATH)/src/drivers/display/st7789 \
$(LVGL_PATH)/src/drivers/evdev \
$(LVGL_PATH)/src/drivers/nuttx \
$(LVGL_PATH)/src/drivers/wayland \
$(LVGL_PATH)/src/drivers/libinput \
$(LVGL_PATH)/src/drivers/glfw \
$(LVGL_PATH)/src/indev \
$(LVGL_PATH)/src/display \
$(LVGL_PATH)/src/osal \
$(LVGL_PATH)/src/misc \
$(LVGL_PATH)/src/misc/cache \
$(LVGL_PATH)/src/misc/cache/instance \
$(LVGL_PATH)/src/misc/cache/class \
$(LVGL_PATH)/src/core \
$(LVGL_PATH)/src/layouts \
$(LVGL_PATH)/src/layouts/flex \
$(LVGL_PATH)/src/layouts/grid \
$(LVGL_PATH)/src/widgets/calendar \
$(LVGL_PATH)/src/widgets/spinner \
$(LVGL_PATH)/src/widgets/switch \
$(LVGL_PATH)/src/widgets/lottie \
$(LVGL_PATH)/src/widgets/table \
$(LVGL_PATH)/src/widgets/tileview \
$(LVGL_PATH)/src/widgets/animimage \
$(LVGL_PATH)/src/widgets/textarea \
$(LVGL_PATH)/src/widgets/menu \
$(LVGL_PATH)/src/widgets/label \
$(LVGL_PATH)/src/widgets/list \
$(LVGL_PATH)/src/widgets/slider \
$(LVGL_PATH)/src/widgets/objx_templ \
$(LVGL_PATH)/src/widgets/imagebutton \
$(LVGL_PATH)/src/widgets/led \
$(LVGL_PATH)/src/widgets/button \
$(LVGL_PATH)/src/widgets/scale \
$(LVGL_PATH)/src/widgets/3dtexture \
$(LVGL_PATH)/src/widgets/msgbox \
$(LVGL_PATH)/src/widgets/image \
$(LVGL_PATH)/src/widgets/dropdown \
$(LVGL_PATH)/src/widgets/canvas \
$(LVGL_PATH)/src/widgets/roller \
$(LVGL_PATH)/src/widgets/win \
$(LVGL_PATH)/src/widgets/spinbox \
$(LVGL_PATH)/src/widgets/line \
$(LVGL_PATH)/src/widgets/property \
$(LVGL_PATH)/src/widgets/span \
$(LVGL_PATH)/src/widgets/chart \
$(LVGL_PATH)/src/widgets/checkbox \
$(LVGL_PATH)/src/widgets/bar \
$(LVGL_PATH)/src/widgets/tabview \
$(LVGL_PATH)/src/widgets/arc \
$(LVGL_PATH)/src/widgets/buttonmatrix \
$(LVGL_PATH)/src/widgets/keyboard \
$(LVGL_PATH)/src/themes \
$(LVGL_PATH)/src/themes/simple \
$(LVGL_PATH)/src/themes/mono \
$(LVGL_PATH)/src/themes/default \
$(LVGL_PATH)/src/tick \
$(LVGL_PATH)/src/font \
$(LVGL_PATH)/src/draw \
$(LVGL_PATH)/src/draw/nema_gfx \
$(LVGL_PATH)/src/draw/sdl \
$(LVGL_PATH)/src/draw/opengles \
$(LVGL_PATH)/src/draw/nxp/vglite \
$(LVGL_PATH)/src/draw/nxp/pxp \
$(LVGL_PATH)/src/draw/nxp/g2d \
$(LVGL_PATH)/src/draw/dma2d \
$(LVGL_PATH)/src/draw/renesas/dave2d \
$(LVGL_PATH)/src/draw/vg_lite \
$(LVGL_PATH)/src/draw/sw \
$(LVGL_PATH)/src/draw/sw/arm2d \
$(LVGL_PATH)/src/draw/sw/blend \
$(LVGL_PATH)/src/draw/sw/blend/arm2d \
$(LVGL_PATH)/src/draw/sw/blend/neon \
$(LVGL_PATH)/src/draw/sw/blend/helium \
$(LVGL_PATH)/src/stdlib \
$(LVGL_PATH)/src/stdlib/uefi \
$(LVGL_PATH)/src/stdlib/rtthread \
$(LVGL_PATH)/src/stdlib/builtin \
$(LVGL_PATH)/src/stdlib/micropython \
$(LVGL_PATH)/src/stdlib/clib \
$(LVGL_PATH)/src/others/test \
$(LVGL_PATH)/src/others/snapshot \
$(LVGL_PATH)/src/others/fragment \
$(LVGL_PATH)/src/others/sysmon \
$(LVGL_PATH)/src/others/observer \
$(LVGL_PATH)/src/others/ime \
$(LVGL_PATH)/src/others/xml \
$(LVGL_PATH)/src/others/xml/parsers \
$(LVGL_PATH)/src/others/imgfont \
$(LVGL_PATH)/src/others/vg_lite_tvg \
$(LVGL_PATH)/src/others/monkey \
$(LVGL_PATH)/src/others/font_manager \
$(LVGL_PATH)/src/others/file_explorer \
$(LVGL_PATH)/src/others/gridnav \
$(LVGL_PATH)/src/libs/thorvg \
$(LVGL_PATH)/src/libs/thorvg/rapidjson \
$(LVGL_PATH)/src/libs/thorvg/rapidjson/error \
$(LVGL_PATH)/src/libs/thorvg/rapidjson/msinttypes \
$(LVGL_PATH)/src/libs/thorvg/rapidjson/internal \
$(LVGL_PATH)/src/libs/tiny_ttf \
$(LVGL_PATH)/src/libs/bin_decoder \
$(LVGL_PATH)/src/libs/qrcode \
$(LVGL_PATH)/src/libs/ffmpeg \
$(LVGL_PATH)/src/libs/gif \
$(LVGL_PATH)/src/libs/svg \
$(LVGL_PATH)/src/libs/rlottie \
$(LVGL_PATH)/src/libs/freetype \
$(LVGL_PATH)/src/libs/barcode \
$(LVGL_PATH)/src/libs/libjpeg_turbo \
$(LVGL_PATH)/src/libs/lodepng \
$(LVGL_PATH)/src/libs/libpng \
$(LVGL_PATH)/src/libs/tjpgd \
$(LVGL_PATH)/src/libs/fsdrv \
$(LVGL_PATH)/src/libs/rle \
$(LVGL_PATH)/src/libs/lz4 \
$(LVGL_PATH)/src/libs/expat \
$(LVGL_PATH)/src/libs/bmp \
